server:
  port: 8080
  servlet:
    context-path: /lnrb
web:
  image-path: E:/image
  upload-path: E:/upload
  file-path: E:/file
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jsboa?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      max-active: 20
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 300MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  resources:
    static-locations: file:${web.image-path},classpath:static/

mybatis:
  mapper-locations:
    - classpath:mappers/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl